--- # Kerberos configuration
- hosts: sssdservers
  vars:
    site: "XYZ"

  tasks:
    - name: Install krb5 and related packages
      yum: pkg={{ item }} state=present
      with_items:
      - krb5-workstation
      - openldap-clients

    - name: Get value of site
      debug: msg="{{ site }}"  
      register: sitedef

    - name: Copy krb5.conf if XYZ
      copy: src=../files/krb5.conf.xyz dest=/etc/krb5.conf owner=root mode=644
      when: '"{{ site }}" == "XYZ"'

