--- # disable selinux
- hosts: sssdservers
  tasks:
    - name: Install libselinux-python
      yum: pkg=libselinux-python state=installed

    - selinux:
        state: disabled
      register: selinuxstatus

    - name: Get status of selinux
      debug: msg="{{ selinuxstatus }}"

