--- # Yum repos for CentOS 6 and RHEL 6
- hosts: sssdservers
  tasks:
    - name: Configure yum repos for CentOS 6
      copy: src=../files/CentOS6-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo owner=root group=root mode=644
      when: (ansible_distribution  == "CentOS") and (ansible_distribution_major_version == "6")

    - name: Configure yum repos for RHEL 6
      copy: src=../files/{{ item }} dest=/etc/yum.repos.d/{{ item }} owner=root group=root mode=644
      with_items: # example of multiple repo items
      - rhel65.repo
      - rhel6-updates.repo
      - epel6.repo
      when: (ansible_distribution == "RedHat") and (ansible_distribution_major_version == "6")

    - name: Clean yum metadata
      shell: "/usr/bin/yum clean metadata"

    - name: Yum update sssd
      shell: '/usr/bin/yum -y update sssd --skip-broken'
      ignore_errors: true
      register: yumupdate
