---
# Ansible NTP playbook to copy file and restart time service
- hosts: ad_servers
  vars:
    - timeserver: '0.rhel.pool.ntp.org'  # set your time server here

  tasks:
    - name: Copy ntp configuration file
      copy: src=files/ntp.conf dest=/etc/ntp.conf owner=root mode=644 backup=no
      register: ntpconf
      notify:
      - restart ntpd
      - force ntp update

    - name: Make sure NTP service is started
      service: name=ntpd state=started enabled=yes
      tags: ntp


  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted 

    - name: force ntp update
      shell: "/sbin/service ntpd stop && /usr/sbin/ntpdate -s {{ timeserver }} && /sbin/service ntpd restart"
