--- # Join MacOSX to AD domain via command line. Requires ssh keys to be set up
- hosts: macgroup
  user: root
  vars:
  - username: ''
  - password: ""
  - DOMAIN: "cooldomain.example.com"
  - OUSTRING: '"OU=Mac,OU=OU123,DC=cooldomain,DC=example,DC=com"'
  - DSCONFIGAD: "/usr/sbin/dsconfigad"
  tasks:
  - name: view current active directory settings
    command: "{{ DSCONFIGAD }} -show"
    register: viewad
  - name: Show results of view AD
    debug: msg={{ viewad }}

  - name: Unbind a computer from active directory domain, before we rejoin it
    command: "{{ DSCONFIGAD }} -remove -username {{ username }} -password {{ password }}"
    ignore_errors: true

  - name: Ensure scutil has set HostName properly
    command: "/usr/sbin/scutil --set HostName {{ ansible_hostname }}"
  - name: Ensure scutil has LocalHostName
    command: "/usr/sbin/scutil --set LocalHostName {{ ansible_hostname }}"
  - name: Ensure scutil has ComputerName
    command: "/usr/sbin/scutil --set ComputerName {{ ansible_hostname }}"
  
  - name: Bind a computer to AD domain
    # For laptops, this creates a local home directory:
    command: "{{ DSCONFIGAD }} -force -add {{ DOMAIN }} -computer {{ ansible_hostname }} -username {{ username }} -password {{ password }} -ou {{ OUSTRING }} -mobile enable -mobileconfirm disable -localhome enable -useuncpath enable -groups 'Domain Admins' -shell /bin/bash "
    register: joinad

  - name: Show results of join ad
    debug: msg={{ joinad }}

  - name: view current active directory settings after join
    command: "{{ DSCONFIGAD }} -show"
    register: viewad
