--- # Join machine to Active Directory 
- hosts: sssdservers
  vars_prompt:
    - name: "username"
      prompt: "Enter username with access to join domain"
      private: no
    - name: "password"
      prompt: "Enter password"
  vars:
   adauth_username: "{{ username }}"
   adauth_password: "{{ password }}"
   ad_OU: "YOUROU"
   ad_full_OU: "TESTDOMAIN/YOUROU/Linux"
   ad_reverse_OU: 'OU=Linux,OU=YOUROU,OU=TESTDOMAIN,DC=testdomain,DC=org'
   ad_domain: 'testdomain.org'
   ad_dc: "dctlr.testdomain.org"


  tasks:
   - name: Install SSSD and related packages
     yum: pkg={{ item }} state=present
     with_items:
     - sssd
     - sssd-client
     - oddjob
     - sssd-ldap
     - adcli
     - pam_ldap
     - openldap-clients
     ignore_errors: true

### Accounts ###
   - name: Check if computer account exists in AD
     command: net ads dn "{{ ad_reverse_OU }}" -S {{ ad_dc }} -U {{ adauth_username }}%{{adauth_password}}
     register: checkadaccount

   - name: Precreate computer account in AD before join
     command: echo -e "{{ adauth_password }}" | adcli preset-computer --domain=testdomain.org --domain-ou="{{ ad_reverse_OU }}" "{{ ansible_fqdn }}" -U "{{ adauth_username }}"
     delegate_to: localhost
     register: createadacct
     when: checkadaccount|failed

   - name: Check status for whether already joined to AD 
     shell: /usr/bin/net ads status -U {{ adauth_username }}%{{ adauth_password }} 
     register: checkjoin
     ignore_errors: true

   - name: Join AD with net ads join command
     command: /usr/bin/net ads join createcomputer="{{ ad_full_OU }}" -U {{adauth_username}}"%"{{adauth_password}}
     ignore_errors: true
     register: join_result
     tags: run_join_ad
     notify: restart sssd

   - name: Show result of join
     debug: msg="{{ join_result }}"

  handlers:
   - name: restart sssd
     service: name=sssd state=restarted enabled=yes
