--- # sshd configuration
- hosts: sssdservers
  tasks:
  - name:  sshd config for /etc/pam.d/sshd
    copy: src=../files/sshd dest=/etc/pam.d/sshd owner=root
    notify:
     - restart sshd
     - restart sssd

  handlers:
  - name: restart sshd
    command: service sshd restart

  - name: restart sssd
    command: service sssd restart
