--- # Configure sssd and its config files
- hosts: sssdservers
  vars:
    default_shell: /bin/bash
    use_fqdn: False
    fallback_homedir: "/users/%u"
    ignore_group_members: "True"


  tasks:
  - name: Install SSSD and related
    yum: pkg={{ item }} state=present
    with_items:
     - sssd
     - sssd-client
     - PackageKit
     - oddjob
     - oddjob-mkhomedir
     - adcli
     - sssd-ldap

  - name: Copy sssd.conf
    copy: src=../files/sssd.conf dest=/etc/sssd/sssd.conf owner=root mode=600

  - name: configure sudoers
    lineinfile: dest=/etc/sudoers line='%admins@domain   ALL=(ALL) ALL'
    tags: add_sudo_user

  - name: Configure default shell
    lineinfile: dest=/etc/sssd/sssd.conf regexp='default_shell' line='default_shell = {{ default_shell }}'
    register: sssd_default_shell
    notify: restart sssd
    tags: default_shell

  - name: Configure ldap_id_mapping
    lineinfile: dest=/etc/sssd/sssd.conf regexp='ldap_id_mapping' backrefs=yes line='ldap_id_mapping = False'
    register: sssd_id_mapping
    notify: restart sssd
    tags: custom_take_uids_from_ldap

  - name: Configure fqdn
    lineinfile: dest=/etc/sssd/sssd.conf regexp='use_fully_qualified_names' line='use_fully_qualified_names = {{ use_fqdn }}'
    register: sssd_fqdn
    notify: restart sssd
    tags: no_fqdn_ad

  - name: Configure fallback user home dir
    lineinfile: dest=/etc/sssd/sssd.conf regexp='fallback_homedir' line='fallback_homedir = {{ fallback_homedir }}'
    register: sssd_conf_fallback
    notify: restart sssd
    tags: custom_home_folder_fallback

  - name: Configure ignore group members to improve lookups in AD
    lineinfile: >
      dest=/etc/sssd/sssd.conf
      regexp='ignore_group_members'
      line='ignore_group_members = {{ ignore_group_members }}'
      state=present
      insertafter=EOF
    register: sssd_ignore_group_members
    notify: restart sssd
    when: ignore_group_members
    tags: custom_no_ad_groups

  - name: Configure dyndns_update 
    lineinfile: dest=/etc/sssd/sssd.conf line='dyndns_update = False'
    register: sssd_conf_dyndns
    notify: restart sssd
    tags: custom_dyndns



  - name: Erase stale sssd data after sssd.conf has changes
    #shell: "systemctl stop sssd; /bin/rm -rf /var/log/sssd/*; /bin/rm -rf /var/lib/sss/db/*"
    shell: "service sssd stop; /bin/rm -rf /var/log/sssd/*; /bin/rm -rf /var/lib/sss/db/*"
    notify: restart sssd
    when: (sssd_idmap_range_min.changed) or
          (sssd_idmap_range_size.changed) or
          (sssd_default_shell.changed) or
          (sssd_id_mapping.changed) or
          (sssd_fqdn.changed) or
          (sssd_conf_fallback.changed) or
          (sssd_ignore_group_members.changed) or
          (sssd_conf_dyndns.changed)
    tags: erase_sssd_database

  - name: Start and enable SSSD at boot
    service: name=sssd state=started enabled=yes
    ignore_errors: true

  handlers:
  - name: restart sssd
    service: name=sssd state=restarted
    ignore_errors: true

