---
# ansible playbook for NIS configuration
- hosts: rhel6:rhel7
  tasks:
    - name: set ypservers
      copy: src=files/yp.conf dest=/etc/yp.conf owner=root
      notify:
      - restart ypbind

    - name: set auto.master
      copy: src=files/auto.master dest=/etc/auto.master owner=root
      notify:
      - restart ypbind

    - name: set nsswitch
      copy: src=files/nsswitch.conf dest=/etc/nsswitch.conf owner=root
      notify:
      - restart ypbind

    - name: set auto.cifs
      copy: src=files/auto.cifs dest=/etc/auto.cifs owner=root
      notify:
      - restart autofs

    - name: check ypbind service
      service: name=ypbind state=started

  handlers:
    - name: restart ypbind
      service: name=ypbind state=restarted enabled=yes
    - name: restart autofs
      service: name=autofs state=restarted enabled=yes
