---
- name: Install Samba
  yum: name={{ item }} state=present
  with_items:
    - samba 
    - samba-client
    - samba-common
    - samba-winbind
    - samba-winbind-clients

- name: Check if samba.conf exists
  stat: path=/etc/samba/smb.conf
  register: stat_result

- name: Copy the samba config file only if not existing to configure as domain member
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=644
  when: stat_result.stat.exists == false
  notify: restart samba

- name: Ensure Samba is started and enabled on boot
  service: name=smb state=started enabled=yes

- name: Join AD with Samba to generate the keytab
  # disabling the next line since we don't need to specify the full OU in our environment
  #command: /usr/bin/net ads join createcomputer={{ adauth_server_ou }} -U "{{ adauth_username }}"%"{{ adauth_password }}"
  command: /usr/bin/net ads join -U "{{ adauth_username }}"%"{{ adauth_password }}"
  args:
    creates: /etc/krb5.keytab

